### PR TITLE
Debian patches: man page, big endian

### PR DESCRIPTION
**Pull request by kilobyte**
Hi, here's a couple of patches that I applied when packaging *lz4json* for Debian:

* man page
* big endian
The latter uses an include file that's in a different path on FreeBSD: we'd need *sys/endian.h* rather than *endian.h*; I did not added detection though — your Makefile doesn't work out of the box there anyway so it's not a regression.

### CODE REVIEW

**Comment by polyzen** [comment]
Might be nice to skip `debian/` and keep the manual in the root dir.

**Comment by kilobyte** [comment]
D'oh!  It was blindly cherry-picked; fixed.

**Comment by andikleen** [comment]
I think what would work for FreeBSD is to add -I /usr/include/sys in the Makefile without needing to detect anything

**Comment by polyzen** [comment]
The readme still mentions requiring a little-endian host.

**Pull request merged**
